language: php

php:
  - 7.1
  - 7.2
  - 7.3

dist: trusty
sudo: required

install:
  - sudo apt-get install expect
  - travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --verbose
